import streamlit as st
import pandas as pd
import joblib
import plotly.graph_objects as go

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO


# ======================================
# Load Model Files
# ======================================

model = joblib.load("models/pcos_model.pkl")
features = joblib.load("models/features.pkl")
defaults = joblib.load("models/default_values.pkl")

comparison = pd.read_csv(
    "reports/model_comparison.csv"
)



# ======================================
# PDF Generator
# ======================================

def generate_pdf(
        risk,
        probability,
        explanation,
        recommendations
):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    content = []


    content.append(
        Paragraph(
            "MediSense AI - PCOS Risk Report",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1,20)
    )


    content.append(
        Paragraph(
            f"Risk Level: {risk}",
            styles["Normal"]
        )
    )


    content.append(
        Paragraph(
            f"Risk Probability: {probability:.2f}%",
            styles["Normal"]
        )
    )


    content.append(
        Spacer(1,20)
    )


    content.append(
        Paragraph(
            "Patient Factors:",
            styles["Heading2"]
        )
    )


    for key,value in explanation.items():

        content.append(
            Paragraph(
                f"{key}: {value}",
                styles["Normal"]
            )
        )


    content.append(
        Spacer(1,20)
    )


    content.append(
        Paragraph(
            "Recommendations:",
            styles["Heading2"]
        )
    )


    for item in recommendations:

        content.append(
            Paragraph(
                "• " + item,
                styles["Normal"]
            )
        )


    content.append(
        Spacer(1,20)
    )


    content.append(
        Paragraph(
            "Generated by MediSense AI",
            styles["Normal"]
        )
    )


    doc.build(content)

    buffer.seek(0)

    return buffer



# ======================================
# Page Configuration
# ======================================

st.set_page_config(
    page_title="MediSense AI",
    page_icon="🩺",
    layout="wide"
)



# ======================================
# Styling
# ======================================

st.markdown(
    """
    <style>

    .title{
        font-size:45px;
        font-weight:700;
        color:#1f4e79;
    }

    .subtitle{
        font-size:22px;
        color:#555;
    }

    </style>
    """,
    unsafe_allow_html=True
)



# ======================================
# Header
# ======================================

st.markdown(
    '<p class="title">🩺 MediSense AI</p>',
    unsafe_allow_html=True
)

st.markdown(
    '<p class="subtitle">AI Powered PCOS Risk Prediction System</p>',
    unsafe_allow_html=True
)


st.write(
"""
MediSense AI predicts PCOS risk using Machine Learning
based on hormonal, ultrasound, symptom and lifestyle factors.
"""
)


st.warning(
"⚠️ This tool is for educational purposes only and does not replace medical advice."
)



# ======================================
# Inputs
# ======================================

input_data = defaults.copy()


st.header("🧬 Hormonal & Ultrasound Parameters")


c1,c2 = st.columns(2)


with c1:

    follicle_r = st.number_input(
        "Right Follicle Count",
        0.0,
        value=5.0
    )


    amh = st.number_input(
        "AMH Level (ng/mL)",
        0.0,
        value=3.0
    )



with c2:

    follicle_l = st.number_input(
        "Left Follicle Count",
        0.0,
        value=5.0
    )


    fsh_lh = st.number_input(
        "FSH/LH Ratio",
        0.0,
        value=1.0
    )



st.header("🩺 Symptoms")


c3,c4,c5 = st.columns(3)


with c3:

    skin = st.selectbox(
        "Skin Darkening",
        ["No","Yes"]
    )


with c4:

    hair = st.selectbox(
        "Hair Growth",
        ["No","Yes"]
    )


with c5:

    weight = st.selectbox(
        "Weight Gain",
        ["No","Yes"]
    )



st.header("🍔 Lifestyle")


fast_food = st.selectbox(
    "Frequent Fast Food Consumption",
    ["No","Yes"]
)



def convert(x):

    return 1 if x=="Yes" else 0



# ======================================
# Prepare Input
# ======================================

input_data["Follicle No. (R)"] = follicle_r
input_data["Follicle No. (L)"] = follicle_l

input_data["AMH(ng/mL)"] = amh

input_data["FSH/LH"] = fsh_lh


input_data["Skin darkening (Y/N)"] = convert(skin)

input_data["hair growth(Y/N)"] = convert(hair)

input_data["Weight gain(Y/N)"] = convert(weight)

input_data["Fast food (Y/N)"] = convert(fast_food)



input_df = pd.DataFrame(
    [input_data]
)


input_df = input_df[features]



# ======================================
# Prediction
# ======================================


if st.button("🔍 Analyze PCOS Risk"):


    prediction = model.predict(input_df)


    probability = model.predict_proba(input_df)[0][1]


    st.divider()

    st.header("📊 AI Assessment")


    if prediction[0]==1:

        risk_status="High Risk"

        st.error(
            "⚠️ Higher possibility of PCOS detected"
        )

    else:

        risk_status="Low Risk"

        st.success(
            "✅ Lower possibility of PCOS detected"
        )



    st.metric(
        "Risk Probability",
        f"{probability*100:.2f}%"
    )



    # Gauge

    st.subheader("🎯 Risk Visualization")


    fig = go.Figure(
        go.Indicator(
            mode="gauge+number",
            value=probability*100,
            title={
                "text":"PCOS Risk Score (%)"
            },
            gauge={
                "axis":{
                    "range":[0,100]
                }
            }
        )
    )


    st.plotly_chart(
        fig,
        use_container_width=True
    )



    # Explainability

    st.divider()

    st.header("🧠 Why this prediction?")


    explanation={

        "Right Follicle Count":follicle_r,
        "Left Follicle Count":follicle_l,
        "AMH Level":amh,
        "FSH/LH Ratio":fsh_lh,
        "Skin Darkening":skin,
        "Hair Growth":hair,
        "Weight Gain":weight,
        "Fast Food Habit":fast_food

    }


    for k,v in explanation.items():

        st.write(
            f"• **{k}:** {v}"
        )



    # Recommendations

    st.divider()

    st.header("💡 Personalized Recommendations")


    recommendations=[]


    if weight=="Yes":

        recommendations.append(
            "Maintain healthy weight through balanced diet and exercise."
        )


    if fast_food=="Yes":

        recommendations.append(
            "Reduce processed and fast food consumption."
        )


    if hair=="Yes":

        recommendations.append(
            "Hair growth may indicate hormonal imbalance. Consider medical evaluation."
        )


    if skin=="Yes":

        recommendations.append(
            "Monitor metabolic health and insulin resistance indicators."
        )


    if amh>5:

        recommendations.append(
            "Higher AMH may require additional hormonal assessment."
        )


    recommendations.append(
        "Track menstrual cycles and maintain regular physical activity."
    )



    for r in recommendations:

        st.write(
            "✅ "+r
        )



    # PDF Download

    st.divider()

    st.header("📄 Download Report")


    pdf = generate_pdf(
        risk_status,
        probability*100,
        explanation,
        recommendations
    )


    st.download_button(
        "⬇️ Download PCOS Report",
        data=pdf,
        file_name="MediSense_PCOS_Report.pdf",
        mime="application/pdf"
    )



# ======================================
# Model Dashboard
# ======================================

st.divider()

st.header("📊 Model Performance Dashboard")


st.dataframe(
    comparison,
    use_container_width=True
)


st.bar_chart(
    comparison.set_index("Model")["Accuracy"]
)


st.success(
"""
Random Forest was selected as the final model due to its superior
accuracy, recall and F1-score.
"""
)



st.divider()

st.caption(
"MediSense AI | Machine Learning Healthcare Assistant"
)